-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("dms ipc call spotlight open"), { description = "Default Launcher: Open" })
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("dms ipc call powermenu open"), { description = "Power Menu: Open" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "terminal" })
hl.unbind("SUPER + SHIFT + E")
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"), { description = "command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'" })
hl.unbind("SUPER + M")
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.window.pseudo({ action = "toggle" }), { description = "pseudo" })
hl.unbind("SUPER + Q")
hl.unbind("SUPER + R")
hl.unbind("SUPER + V")
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("dms ipc call island open wallpaper"), { description = "DankIsland: Open Wallpapers" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle Floating" })
